### ISSUE TITLE
Expand installation instructions for Grafanna setup

### ISSUE THREAD

**Issue by kmanwar89** [smilebasti/npmGrafStats#14]
The instructions mention setting up a data source, but there's *lots* of other options that need to be filled out - can the instructions go into more details, please?

For instance, where does the API key go? Which Query language should be used? Any custom headers?

Screenshot shows the available options:

![image](https://github.com/smilebasti/npmGrafStats/assets/11323060/83ca33df-8de7-4396-8519-2d7cf74e027f)

Please let me know if I can help - I'd be happy to submit a PR, thanks!

**Comment by smilebasti** [comment]
Hi, thanks for the Issue.

Is this more useful? https://github.com/smilebasti/npmGrafStats/wiki/Grafana-installation

**Comment by obsidiangroup** [comment]
> Hi, thanks for the Issue.
> 
> Is this more useful? https://github.com/smilebasti/npmGrafStats/wiki/Grafana-installation

Is setting the organization to 'npmgrafstats' required?

I'm running into issues trying to run two separate instances of npmGrafStats, both pointed to the same InfluxDB but different buckets.

I wanted a dashboard that also included stats on my local-ips, which by default are filtered, so I made some changes to the two scripts and the Getipinfo.py.  This version works with no issues.  

I deployed a second container with no modifications and pointed it to a separate bucket.  There is data in the bucket, but the Grafana dashboard is empty.

**Comment by smilebasti** [comment]
Interesting to hear.

The Grafana Dashboard has the bucket hardcoded:
```
from(bucket: "npmgrafstats")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._field == "Domain")
  |> group(columns: ["Domain"])
  |> count()
  |> drop(columns: ["host", "_field", "_measurement", "_start", "_stop"])
```

The organization is not. Maybe sending the npmGrafStats data to two different organizations both with a bucket called npmgrafstats.
Or you change the `from(bucket: "npmgrafstats")` in every panel to your needs.

**Comment by obsidiangroup** [comment]
> Or you change the `from(bucket: "npmgrafstats")` in every panel to your needs.

You know I looked at the query and saw that but it didn't register.  Updating does correct that.  

Instead of hardcoding, would it be possible to obtain the default bucket that you've defined in your datasources?  Or, maybe add to the documentation that if you're running multiple instances on the same influxdb, to use different organizations?

As I said, the only reason I did this was I wanted a dashboard that showed local stats.  Maybe a config option to track internal/local stats.  Since obviously if you pass an RFC1918 address to `response = reader.city(str(sys.argv[1]))` will result in an error, if the ip is in my block, it instead uses response = `reader.city(os.getenv('HOME_IPS'))`.

I could possibly submit a PR that adds this as an option.

**Comment by smilebasti** [comment]
Ok good.

I will have a look at the Grafana Flux query if it accepts the default bucket. Anyway i will add the separate organization to the wiki.

With Issue #15 the HOME_IPS variable can be replaced. Maybe I can replace it with the option to monitor internal calls.
